import __builtin__

__builtin__.CLIENT_LOGIN_TOONTOWN = 125

__builtin__.CLIENT_GO_GET_LOST = 4

__builtin__.CLIENT_SYSTEM_MESSAGE = 78
__builtin__.CLIENT_SYSTEMMESSAGE_AKNOWLEDGE = 123

__builtin__.CLIENT_CREATE_OBJECT_REQUIRED = 34
__builtin__.CLIENT_CREATE_OBJECT_REQUIRED_OTHER = 35
__builtin__.CLIENT_CREATE_OBJECT_REQUIRED_OTHER_OWNER = 36

__builtin__.CLIENT_OBJECT_UPDATE_FIELD = 24

__builtin__.CLIENT_OBJECT_DISABLE = 25
__builtin__.CLIENT_OBJECT_DISABLE_OWNER = 26
__builtin__.CLIENT_OBJECT_DELETE_RESP = 27

__builtin__.CLIENT_GET_STATE_RESP = 47

__builtin__.CLIENT_SET_WISHNAME_RESP = 71

__builtin__.CLIENT_LOGIN_2 = 16
__builtin__.CLIENT_LOGIN_2_RESP = 17

__builtin__.CLIENT_LOGIN_RESP = 2
__builtin__.CLIENT_LOGIN_3_RESP = 110
__builtin__.CLIENT_LOGIN_3 = 111
__builtin__.CLIENT_LOGIN_TOONTOWN_RESP = 126

__builtin__.CLIENT_GET_AVATARS = 3
__builtin__.CLIENT_GET_AVATARS_RESP = 5

__builtin__.CLIENT_CREATE_AVATAR = 6
__builtin__.CLIENT_CREATE_AVATAR_RESP = 7

__builtin__.CLIENT_GET_AVATARS_RESP2 = 75

__builtin__.CLIENT_SET_AVATAR = 32
__builtin__.CLIENT_GET_AVATAR_DETAILS_RESP = 15

__builtin__.CLIENT_GET_FRIEND_LIST = 10
__builtin__.CLIENT_GET_FRIEND_LIST_RESP = 11

__builtin__.CLIENT_GET_FRIEND_LIST_EXTENDED_RESP = 116

__builtin__.CLIENT_FRIEND_ONLINE = 53
__builtin__.CLIENT_FRIEND_OFFLINE = 54

__builtin__.CLIENT_GET_PET_DETAILS_RESP = 82

__builtin__.CLIENT_OBJECT_DISABLE_RESP = 25

__builtin__.CLIENT_GET_AVATAR_DETAILS = 14

__builtin__.CLIENT_SET_WISHNAME_CLEAR = 72
__builtin__.CLIENT_SET_WISHNAME = 70

__builtin__.CLIENT_SET_AVTYPE = 80