import builtins

builtins.CLIENT_LOGIN_TOONTOWN = 125

builtins.CLIENT_GO_GET_LOST = 4

builtins.CLIENT_SYSTEM_MESSAGE = 78
builtins.CLIENT_SYSTEMMESSAGE_AKNOWLEDGE = 123

builtins.CLIENT_CREATE_OBJECT_REQUIRED = 34
builtins.CLIENT_CREATE_OBJECT_REQUIRED_OTHER = 35
builtins.CLIENT_CREATE_OBJECT_REQUIRED_OTHER_OWNER = 36

builtins.CLIENT_OBJECT_UPDATE_FIELD = 24

builtins.CLIENT_OBJECT_DISABLE = 25
builtins.CLIENT_OBJECT_DISABLE_OWNER = 26
builtins.CLIENT_OBJECT_DELETE_RESP = 27

builtins.CLIENT_GET_STATE_RESP = 47

builtins.CLIENT_SET_WISHNAME_RESP = 71

builtins.CLIENT_LOGIN_2_RESP = 17
builtins.CLIENT_LOGIN_RESP = 2
builtins.CLIENT_LOGIN_3_RESP = 110
builtins.CLIENT_LOGIN_TOONTOWN_RESP = 126

builtins.CLIENT_GET_AVATARS = 3
builtins.CLIENT_GET_AVATARS_RESP = 5

builtins.CLIENT_CREATE_AVATAR = 6
builtins.CLIENT_CREATE_AVATAR_RESP = 7

builtins.CLIENT_GET_AVATARS_RESP2 = 75

builtins.CLIENT_SET_AVATAR = 32
builtins.CLIENT_GET_AVATAR_DETAILS_RESP = 15

builtins.CLIENT_GET_FRIEND_LIST = 10
builtins.CLIENT_GET_FRIEND_LIST_RESP = 11

builtins.CLIENT_GET_FRIEND_LIST_EXTENDED_RESP = 116

builtins.CLIENT_FRIEND_ONLINE = 53
builtins.CLIENT_FRIEND_OFFLINE = 54

builtins.CLIENT_GET_PET_DETAILS_RESP = 82

builtins.CLIENT_OBJECT_DISABLE_RESP = 25

builtins.CLIENT_GET_AVATAR_DETAILS = 14